# Generated by Django 3.2.8 on 2021-11-21 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_detailed_data_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
